### ISSUE TITLE
Wether or not to submit slides that aren't self contained, and rely heavily on the talk

### ISSUE THREAD

**Issue by hameerabbasi** [deniederhut/Slides-SciPyConf-2018#33]
As title.

**Comment by deniederhut** [comment]
It's up to you! If you would have a reason to share the slides instead of your paper (or with your paper), then this repo is a place for you to put it to make it easier for people to find.

**Comment by hameerabbasi** [comment]
Probably not, they will be of very little value. Thanks though!
